workflows:
  saeed-notes-ios:
    name: Saeed Notes iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Add iOS Platform
        script: |
          flutter create --platforms=ios .
          cd ios && pod install
      - name: Build iOS
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
